[package]
name = "monkey_interpreter"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "monkeyinterpreter"

[dependencies]
once_cell = "1.18.0"
unindent = "0.2.1"
whoami = "1.4.1"
